name: ia753
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - pytest
  - black
  - mypy
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - ipykernel
  - ipython
  - ipywidgets
  - pip:
    - -r file:requirements.txt
